### ISSUE TITLE
[TO-DO] 함께해요 봉사 신청 관련 해결해야 할 것

### ISSUE THREAD

**Issue by minsungbyun** [minsungbyun/happy-share#28]
- [ ] 개인 owner joinDTO로 변경 name 추가 기관 변경 필요!
- [ ] 참여자 목록 카운트가 총 인원을 넘었는데도 올라간다.
- [ ] 참여자 목록을 조회할 때도 카운트다 올라간다.
- [ ] 주최자가 봉사신청을 한다? 자동으로 멤버에 들어가게끔 해야한다.
- [ ] 봉사 번호는 자동으로 부여하게 해야한다.   
- [ ] 중복제거
- [ ] 관리자가 중복으로 봉사신청 승인가능한 문제
- [ ] 봉사시작 반복문제

**Comment by minsungbyun** [comment]
- [ ] 회원 탈퇴할 때 초기화면에 로그인이 떠야하는데 
- [ ] 봉사 다른 번호 입력했을때 유효성 검사
- [ ] 회원정보 저장하면 봉사인원 저장이 안된다.
